# Generated by Django 6.0.3 on 2026-04-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField()),
                ('budget', models.CharField(max_length=20)),
                ('climate', models.CharField(max_length=20)),
                ('interests', models.JSONField()),
                ('restrictions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
