# Generated by Django 5.2.1 on 2026-04-30 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelerdnaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_dna_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertrippreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
