# Generated by Django 5.2.1 on 2026-04-30 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_initial'),
        ('itineraries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteitinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriteitinerary',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='itinerarydailyevent',
            name='poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_events', to='destinations.pointofinterest'),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='itinerarydailyevent',
            name='itinerary_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='itineraries.itineraryday'),
        ),
        migrations.AddField(
            model_name='review',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='itinerary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_stats', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='shareditinerarylink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareditinerarylink',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='itineraries.itinerary'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteitinerary',
            unique_together={('user', 'itinerary')},
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('itinerary', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('itinerary', 'user')},
        ),
    ]
