# Generated by Django 6.0.3 on 2026-04-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('destino_principal', models.CharField(max_length=255)),
                ('dados', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('saved', 'Salvo'), ('edited', 'Editado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
