# Generated by Django 6.0.3 on 2026-04-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        ('travelplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='travel_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelplans.travelplan'),
        ),
    ]
