# Generated by Django 6.0.3 on 2026-04-07 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='A nota mínima é 0.'), django.core.validators.MaxValueValidator(10, message='A nota máxima é 10.')]),
        ),
    ]
