# Generated by Django 5.2.1 on 2026-04-30 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('best_season', models.CharField(blank=True, max_length=120)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationCostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='BRL', max_length=3)),
                ('daily_budget_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_budget_mid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_budget_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('poi_type', models.CharField(choices=[('attraction', 'Attraction'), ('restaurant', 'Restaurant'), ('activity', 'Activity'), ('lodging', 'Lodging')], max_length=24)),
                ('summary', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('opening_hours', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('price_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('estimated_visit_minutes', models.PositiveIntegerField(default=90)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POITag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
