# Generated by Django 5.2.1 on 2026-04-30 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinationcostprofile',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_profile', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pois', to='destinations.poitag'),
        ),
        migrations.AlterUniqueTogether(
            name='pointofinterest',
            unique_together={('destination', 'slug')},
        ),
    ]
