# Generated by Django 5.2.1 on 2026-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
