# Generated by Django 6.0.3 on 2026-04-07 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_type', models.CharField(max_length=20)),
                ('comfort_level', models.CharField(max_length=20)),
                ('companionship', models.CharField(max_length=20)),
                ('travel_pace', models.CharField(max_length=20)),
                ('travel_experience', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
